apiVersion: v1
kind: Namespace
metadata:
  name: argocddemo
  labels:
    app.kubernetes.io/name: argocddemo

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: argocddemo-quota
  namespace: argocddemo
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "20"
    services.loadbalancer: "1"
    services.nodeport: "0"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: argocddemo-limits
  namespace: argocddemo
spec:
  limits:
    - default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "1"
        memory: 512Mi
      min:
        cpu: 10m
        memory: 32Mi
      type: Container
