apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: argocddemo
  labels:
    app.kubernetes.io/name: argocddemo
    app.kubernetes.io/component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocddemo
      app.kubernetes.io/component: backend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: argocddemo
  labels:
    app.kubernetes.io/name: argocddemo
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocddemo
      app.kubernetes.io/component: frontend
